In [4]:
import numpy as np
import pandas as pd

In [5]:
clean = pd.read_csv("./northwind_orders.csv")
clean.head(5)

,order_id,customer_id,employee_id,order_date,required_date,shipped_date,ship_via,freight,ship_name,ship_address,ship_city,ship_region,ship_postal_code,ship_country
0,10248,VINET,5,1996-07-04,1996-08-01,1996-07-16,3,32.38,Vins et alcools Chevalier,59 rue de l'Abbaye,Reims,NaN,51100,France
1,10249,TOMSP,6,1996-07-05,1996-08-16,1996-07-10,1,11.61,Toms Spezialitäten,Luisenstr. 48,Münster,NaN,44087,Germany
2,10250,HANAR,4,1996-07-08,1996-08-05,1996-07-12,2,65.83,Hanari Carnes,"Rua do Paço, 67",Rio de Janeiro,RJ,05454-876,Brazil
3,10251,VICTE,3,1996-07-08,1996-08-05,1996-07-15,1,41.34,Victuailles en stock,"2, rue du Commerce",Lyon,NaN,69004,France
4,10252,SUPRD,4,1996-07-09,1996-08-06,1996-07-11,2,51.30,Suprêmes délices,"Boulevard Tirou, 255",Charleroi,NaN,B-6000,Belgium

In [6]:
clean.isnull().sum()

order_id              0
customer_id           0
employee_id           0
order_date            0
required_date         0
shipped_date         21
ship_via              0
freight               0
ship_name             0
ship_address          0
ship_city             0
ship_region         507
ship_postal_code     19
ship_country          0
dtype: int64

In [7]:
clean.shape

(830, 14)

In [8]:
clean.isnull().sum()

order_id              0
customer_id           0
employee_id           0
order_date            0
required_date         0
shipped_date         21
ship_via              0
freight               0
ship_name             0
ship_address          0
ship_city             0
ship_region         507
ship_postal_code     19
ship_country          0
dtype: int64

In [9]:
new[new['ship_postal_code'].isnull()]
new.head(5)

NameError: name 'new' is not defined

In [ ]:
clean.dtypes

order_id                     int64
customer_id                    str
employee_id                  int64
order_date          datetime64[us]
required_date                  str
shipped_date                   str
ship_via                     int64
freight                    float64
ship_name                      str
ship_address                   str
ship_city                      str
ship_region                    str
ship_postal_code               str
ship_country                   str
dtype: object

In [ ]:
clean['order_date'] = pd.to_datetime(clean['order_date'])
clean['order_date']

0     1996-07-04
1     1996-07-05
2     1996-07-08
3     1996-07-08
4     1996-07-09
         ...
825   1998-05-05
826   1998-05-06
827   1998-05-06
828   1998-05-06
829   1998-05-06
Name: order_date, Length: 830, dtype: datetime64[us]

In [ ]:
clean['required_date'] = pd.to_datetime(clean['required_date'])
clean['required_date']

0     1996-08-01
1     1996-08-16
2     1996-08-05
3     1996-08-05
4     1996-08-06
         ...
825   1998-06-02
826   1998-06-03
827   1998-06-03
828   1998-06-03
829   1998-06-03
Name: required_date, Length: 830, dtype: datetime64[us]

In [ ]:
clean['shipped_date'] = pd.to_datetime(clean['shipped_date'])
clean['shipped_date']

0     1996-07-16
1     1996-07-10
2     1996-07-12
3     1996-07-15
4     1996-07-11
         ...
825          NaT
826          NaT
827          NaT
828          NaT
829          NaT
Name: shipped_date, Length: 830, dtype: datetime64[us]

In [ ]:
clean.dtypes

order_id                     int64
customer_id                    str
employee_id                  int64
order_date          datetime64[us]
required_date       datetime64[us]
shipped_date        datetime64[us]
ship_via                     int64
freight                    float64
ship_name                      str
ship_address                   str
ship_city                      str
ship_region                    str
ship_postal_code               str
ship_country                   str
dtype: object

In [13]:
clean.shape

(830, 14)

In [11]:
clean.to_csv('clean_orders.csv', index=False, na_rep='\\N')
clean

,order_id,customer_id,employee_id,order_date,required_date,shipped_date,ship_via,freight,ship_name,ship_address,ship_city,ship_region,ship_postal_code,ship_country
0,10248,VINET,5,1996-07-04,1996-08-01,1996-07-16,3,32.38,Vins et alcools Chevalier,59 rue de l'Abbaye,Reims,NaN,51100,France
1,10249,TOMSP,6,1996-07-05,1996-08-16,1996-07-10,1,11.61,Toms Spezialitäten,Luisenstr. 48,Münster,NaN,44087,Germany
2,10250,HANAR,4,1996-07-08,1996-08-05,1996-07-12,2,65.83,Hanari Carnes,"Rua do Paço, 67",Rio de Janeiro,RJ,05454-876,Brazil
3,10251,VICTE,3,1996-07-08,1996-08-05,1996-07-15,1,41.34,Victuailles en stock,"2, rue du Commerce",Lyon,NaN,69004,France
4,10252,SUPRD,4,1996-07-09,1996-08-06,1996-07-11,2,51.30,Suprêmes délices,"Boulevard Tirou, 255",Charleroi,NaN,B-6000,Belgium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
825,11073,PERIC,2,1998-05-05,1998-06-02,NaN,2,24.95,Pericles Comidas clásicas,Calle Dr. Jorge Cash 321,México D.F.,NaN,05033,Mexico
826,11074,SIMOB,7,1998-05-06,1998-06-03,NaN,2,18.44,Simons bistro,Vinbæltet 34,Kobenhavn,NaN,1734,Denmark
827,11075,RICSU,8,1998-05-06,1998-06-03,NaN,2,6.19,Richter Supermarkt,Starenweg 5,Genève,NaN,1204,Switzerland
828,11076,BONAP,4,1998-05-06,1998-06-03,NaN,2,38.28,Bon app',"12, rue des Bouchers",Marseille,NaN,13008,France
829,11077,RATTC,1,1998-05-06,1998-06-03,NaN,2,8.53,Rattlesnake Canyon Grocery,2817 Milton Dr.,Albuquerque,NM,87110,USA

In [12]:
clean.isnull().sum()

order_id              0
customer_id           0
employee_id           0
order_date            0
required_date         0
shipped_date         21
ship_via              0
freight               0
ship_name             0
ship_address          0
ship_city             0
ship_region         507
ship_postal_code     19
ship_country          0
dtype: int64

In [ ]:
clean.dtypes

order_id                     int64
customer_id                    str
employee_id                  int64
order_date          datetime64[us]
required_date       datetime64[us]
shipped_date        datetime64[us]
ship_via                     int64
freight                    float64
ship_name                      str
ship_address                   str
ship_city                      str
ship_region                    str
ship_postal_code               str
ship_country                   str
dtype: object

In [ ]:
clean[clean['ship_region'].isnull()]

,order_id,customer_id,employee_id,order_date,required_date,shipped_date,ship_via,freight,ship_name,ship_address,ship_city,ship_region,ship_postal_code,ship_country
0,10248,VINET,5,1996-07-04,1996-08-01,1996-07-16,3,32.38,Vins et alcools Chevalier,59 rue de l'Abbaye,Reims,NaN,51100,France
1,10249,TOMSP,6,1996-07-05,1996-08-16,1996-07-10,1,11.61,Toms Spezialitäten,Luisenstr. 48,Münster,NaN,44087,Germany
3,10251,VICTE,3,1996-07-08,1996-08-05,1996-07-15,1,41.34,Victuailles en stock,"2, rue du Commerce",Lyon,NaN,69004,France
4,10252,SUPRD,4,1996-07-09,1996-08-06,1996-07-11,2,51.30,Suprêmes délices,"Boulevard Tirou, 255",Charleroi,NaN,B-6000,Belgium
6,10254,CHOPS,5,1996-07-11,1996-08-08,1996-07-23,2,22.98,Chop-suey Chinese,Hauptstr. 31,Bern,NaN,3012,Switzerland
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
824,11072,ERNSH,4,1998-05-05,1998-06-02,NaT,2,258.64,Ernst Handel,Kirchgasse 6,Graz,NaN,8010,Austria
825,11073,PERIC,2,1998-05-05,1998-06-02,NaT,2,24.95,Pericles Comidas clásicas,Calle Dr. Jorge Cash 321,México D.F.,NaN,05033,Mexico
826,11074,SIMOB,7,1998-05-06,1998-06-03,NaT,2,18.44,Simons bistro,Vinbæltet 34,Kobenhavn,NaN,1734,Denmark
827,11075,RICSU,8,1998-05-06,1998-06-03,NaT,2,6.19,Richter Supermarkt,Starenweg 5,Genève,NaN,1204,Switzerland
828,11076,BONAP,4,1998-05-06,1998-06-03,NaT,2,38.28,Bon app',"12, rue des Bouchers",Marseille,NaN,13008,France